test: &default
  adapter: postgresql
  encoding: unicode
  database: data_guard_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 16
  reaping_frequency: 10
  user: dmitry

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  database: data_guard

development:
  <<: *default
  database: data_guard
